openapi: 3.0.3
info:
  title: Todo Backend API with JWT Authentication
  description: Backend Core & Database Layer for Multi-User Todo Application with JWT-based Authentication
  version: 0.1.0
paths:
  /api/{user_id}/tasks:
    get:
      summary: Get tasks for a specific user
      description: Retrieve all tasks for the authenticated user. Requires valid JWT token.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose tasks to retrieve
          schema:
            type: integer
        - name: completed
          in: query
          required: false
          description: Filter tasks by completion status
          schema:
            type: boolean
        - name: priority
          in: query
          required: false
          description: Filter tasks by priority level
          schema:
            type: string
            enum: [high, medium, low]
        - name: tag
          in: query
          required: false
          description: Filter tasks by tag
          schema:
            type: string
        - name: search
          in: query
          required: false
          description: Search tasks by title or description
          schema:
            type: string
        - name: sort_by
          in: query
          required: false
          description: Sort tasks by field
          schema:
            type: string
            enum: [due_date, priority, title]
            default: due_date
        - name: order
          in: query
          required: false
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
            default: asc
      responses:
        '200':
          description: List of tasks for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User trying to access another user's tasks
        '422':
          description: Validation error
      security:
        - bearerAuth: []
    post:
      summary: Create a new task for a user
      description: Create a new task for the authenticated user. Requires valid JWT token.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user creating the task
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User trying to create task for another user
        '422':
          description: Validation error
      security:
        - bearerAuth: []
  /api/{user_id}/tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task for the authenticated user. Requires valid JWT token.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose task to retrieve
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User trying to access another user's task
        '404':
          description: Task not found
        '422':
          description: Validation error
      security:
        - bearerAuth: []
    put:
      summary: Update a specific task
      description: Update a specific task for the authenticated user. Requires valid JWT token.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose task to update
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User trying to update another user's task
        '404':
          description: Task not found
        '422':
          description: Validation error
      security:
        - bearerAuth: []
    delete:
      summary: Delete a specific task
      description: Delete a specific task for the authenticated user. Requires valid JWT token.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose task to delete
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User trying to delete another user's task
        '404':
          description: Task not found
        '422':
          description: Validation error
      security:
        - bearerAuth: []
  /api/{user_id}/tasks/{task_id}/complete:
    patch:
      summary: Toggle task completion status
      description: Toggle the completion status of a specific task for the authenticated user. Requires valid JWT token.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose task to update
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskToggleComplete'
      responses:
        '200':
          description: Task completion status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User trying to update another user's task
        '404':
          description: Task not found
        '422':
          description: Validation error
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - completed
        - priority
        - user_id
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique identifier for the task
        title:
          type: string
          maxLength: 255
          description: Task title
        description:
          type: string
          maxLength: 1000
          description: Task description (optional)
        completed:
          type: boolean
          description: Whether the task is completed
        priority:
          type: string
          enum: [high, medium, low]
          description: Task priority level
        tags:
          type: string
          maxLength: 500
          description: Comma-separated tags for the task
        due_date:
          type: string
          format: date-time
          description: Due date for the task (optional)
        user_id:
          type: integer
          description: ID of the user who owns the task
        created_at:
          type: string
          format: date-time
          description: Timestamp when the task was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
    TaskCreate:
      type: object
      required:
        - title
        - user_id
      properties:
        title:
          type: string
          maxLength: 255
          description: Task title
        description:
          type: string
          maxLength: 1000
          description: Task description (optional)
        completed:
          type: boolean
          description: Whether the task is completed (default: false)
        priority:
          type: string
          enum: [high, medium, low]
          description: Task priority level (default: medium)
        tags:
          type: string
          maxLength: 500
          description: Comma-separated tags for the task
        due_date:
          type: string
          format: date-time
          description: Due date for the task (optional)
        user_id:
          type: integer
          description: ID of the user who owns the task
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
          description: Task title
        description:
          type: string
          maxLength: 1000
          description: Task description (optional)
        completed:
          type: boolean
          description: Whether the task is completed
        priority:
          type: string
          enum: [high, medium, low]
          description: Task priority level
        tags:
          type: string
          maxLength: 500
          description: Comma-separated tags for the task
        due_date:
          type: string
          format: date-time
          description: Due date for the task (optional)
    TaskToggleComplete:
      type: object
      required:
        - completed
      properties:
        completed:
          type: boolean
          description: New completion status for the task