apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-chatbot.backend.selectorLabels" . | nindent 4 }}
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "todo-chatbot.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-chatbot.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: todo-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.configMapRef }}
          env:
            - name: HOST
              value: {{ .Values.backend.env.HOST | quote }}
            - name: PORT
              value: {{ .Values.backend.env.PORT | quote }}
            - name: CORS_ORIGINS
              value: {{ .Values.backend.env.CORS_ORIGINS | quote }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.httpGet.path }}
              port: {{ .Values.backend.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.httpGet.path }}
              port: {{ .Values.backend.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu | quote }}
              memory: {{ .Values.backend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu | quote }}
              memory: {{ .Values.backend.resources.limits.memory | quote }}
